version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.0.14-browsers
      - image: cimg/mysql:5.7
    environment:
      - APP_KEY: base64:oQmNMb3MkWL+DCmtghmldg2hXKbthkWyjVFaYUW7618=
      - APP_DEBUG: true
      - APP_ENV: testing
      - DB_CONNECTION: circle_test
      - DB_DATABASE: vuelaradb_test
      - DB_USERNAME: root
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
      - MYSQL_DATABASE: vuelaradb_test

    steps:
      - checkout

      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}

      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run dev

      - run:
          name: php test
          command: vendor/bin/phpunit
