version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.0.14-browsers
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_DB: vuelaradb_test
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret

    environment:
      APP_KEY: base64:oQmNMb3MkWL+DCmtghmldg2hXKbthkWyjVFaYUW7618=
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: vuelaradb_test
      DB_USERNAME: default
      DB_PASSWORD: secret

    steps:
      - checkout
      # PHP関連パッケージのインストールエラー対策
      # - run: sudo composer self-update --1

      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}

      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run dev

      - run:
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql
            dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: php test
          command: vendor/bin/phpunit
